version: '3'
services:
  app:
    build:
      context: ../
    ports:
      - "${APP_PORT}8080"
    volumes:
      - ../:/app

  invoice-generator-microservice:
    image: feejkr/invoice-generator
    ports:
      - "${HTML2PDF_MICROSERVICE_PORT}3000"
    hostname: invoice-generator-ms

  db:
    image: "postgres:latest"
    ports:
      - "${SQL_DATABASE_PORT}5432"
    environment:
      - POSTGRES_USER=${SQL_DATABASE_USER}
      - POSTGRES_PASSWORD=${SQL_DATABASE_PASSWORD}
      - PGPASSWORD=${SQL_DATABASE_ROOT_PASSWORD}
