<?php

declare(strict_types=1);

namespace App\Modules\Invoices\Infrastructure\Domain\Invoice;

use App\Modules\Invoices\Application\Filesystem\MoveFileToDropbox\MoveFileToDropboxCommand;
use App\Modules\Invoices\Domain\Invoice\HtmlGenerator;
use App\Modules\Invoices\Domain\Invoice\PdfFromHtmlGenerator as PdfFromHtmlGeneratorInterface;
use App\Modules\Invoices\Domain\Invoice\Invoice;
use GuzzleHttp\Client;
use Ramsey\Uuid\Uuid;
use Symfony\Component\Messenger\MessageBusInterface;

class PdfFromHtmlGenerator implements PdfFromHtmlGeneratorInterface
{
    public function __construct(
        private Client $httpClient,
        private MessageBusInterface $bus,
        private HtmlGenerator $htmlGenerator,
        private string $host,
    ){}

    public function generate(Invoice $invoice): void
    {
        $filepath = sprintf('generated-files/%s.pdf', $invoice->getId()->toString());

        $this->httpClient->post(sprintf('%s/v1/invoice/generate', rtrim($this->host, '/')), [
            'json' => [
                'parameters' => $this->htmlGenerator->prepareParameters($invoice),
                'country' => 'pl',
            ],
            'sink' => $filepath,
        ]);

        $this->bus->dispatch(
            new MoveFileToDropboxCommand(
                $filepath,
                sprintf('/autogenerated/%s.pdf', $invoice->getId()->toString())
            )
        );
    }
}