<?php
declare(strict_types=1);

namespace App\Modules\Invoices\Infrastructure\Domain\Invoice;

use App\Modules\Invoices\Application\Filesystem\MoveFileToDropbox\MoveFileToDropboxCommand;
use App\Modules\Invoices\Domain\Invoice\HtmlGenerator;
use App\Modules\Invoices\Domain\Invoice\PdfFromHtmlGenerator as PdfFromHtmlGeneratorInterface;
use App\Modules\Invoices\Domain\Invoice\Invoice;
use GuzzleHttp\Client;
use Ramsey\Uuid\Uuid;
use Symfony\Component\Messenger\MessageBusInterface;

class PdfFromHtmlGenerator implements PdfFromHtmlGeneratorInterface
{
    public function __construct(
        private Client $httpClient,
        private MessageBusInterface $bus,
        private HtmlGenerator $htmlGenerator,
        private string $host,
    ){}

    public function generate(Invoice $invoice): void
    {
        $uuid = Uuid::uuid4()->toString();
        $filepath = sprintf('generated-files/%s-invoice.pdf', $uuid);

        $this->httpClient->post(sprintf('%s/html-to-pdf', rtrim($this->host, '/')), [
            'json' => ['html' => $this->htmlGenerator->generate($invoice)],
            'sink' => $filepath,
        ]);

        $this->bus->dispatch(
            new MoveFileToDropboxCommand(
                $filepath,
                sprintf('/autogenerated/%s-invoice.pdf', $uuid)
            )
        );
    }
}