<?php
declare(strict_types=1);

namespace App\Modules\Invoices\Infrastructure\Domain\Filesystem;

use App\Modules\Invoices\Domain\Filesystem\Dropbox;
use Exception;
use GuzzleHttp\Client;

class DropboxApiIntegration implements Dropbox
{
    private const DROPBOX_UPLOAD_URL = 'https://content.dropboxapi.com/2/files/upload';

    private const DROPBOX_DEFAULT_TARGET_PATH = '/autogenerated/';

    public function __construct(private Client $httpClient, private string $dropboxAuthorizationToken){}

    public function upload(string $filepath, ?string $customTargetPath = null): void
    {
        try {
            $file = fopen($filepath, 'rb');
            $targetPath = sprintf(
                '%s/%s',
                rtrim($customTargetPath ?? self::DROPBOX_DEFAULT_TARGET_PATH, '/'),
                $filepath
            );

            $this->httpClient->post(self::DROPBOX_UPLOAD_URL, [
                'headers' => [
                    'Authorization' => sprintf('Bearer %s', $this->dropboxAuthorizationToken),
                    'Content-Type' => 'application/octet-stream',
                    'Dropbox-API-Arg' => json_encode(['path' => $targetPath], JSON_THROW_ON_ERROR),
                ],
                'body' => $file,
            ]);
        } catch (\Throwable $exception) {
            throw new Exception($exception->getMessage());
        }
    }
}